// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mesh-packet.proto

package rem

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ForwardingType int32

const (
	ForwardingType_no_FORWARD        ForwardingType = 0
	ForwardingType_TO_ROOT           ForwardingType = 1
	ForwardingType_RTN_HEADER_QUEUE  ForwardingType = 2
	ForwardingType_TO_PARENT_TO_ROOT ForwardingType = 3
	ForwardingType_TO_PARENT         ForwardingType = 4
	ForwardingType_TO_CHILD          ForwardingType = 5
	ForwardingType_TO_NEIGHBORS      ForwardingType = 6
	ForwardingType_TO_NODE           ForwardingType = 7
	ForwardingType_NEIGHBOR_STOP     ForwardingType = 10
	ForwardingType_NEIGHBOR_TO_ROOT  ForwardingType = 11
	ForwardingType_NEIGHBOR_AND_BACK ForwardingType = 12
	ForwardingType_PARENT_AND_BACK   ForwardingType = 22
)

var ForwardingType_name = map[int32]string{
	0:  "no_FORWARD",
	1:  "TO_ROOT",
	2:  "RTN_HEADER_QUEUE",
	3:  "TO_PARENT_TO_ROOT",
	4:  "TO_PARENT",
	5:  "TO_CHILD",
	6:  "TO_NEIGHBORS",
	7:  "TO_NODE",
	10: "NEIGHBOR_STOP",
	11: "NEIGHBOR_TO_ROOT",
	12: "NEIGHBOR_AND_BACK",
	22: "PARENT_AND_BACK",
}
var ForwardingType_value = map[string]int32{
	"no_FORWARD":        0,
	"TO_ROOT":           1,
	"RTN_HEADER_QUEUE":  2,
	"TO_PARENT_TO_ROOT": 3,
	"TO_PARENT":         4,
	"TO_CHILD":          5,
	"TO_NEIGHBORS":      6,
	"TO_NODE":           7,
	"NEIGHBOR_STOP":     10,
	"NEIGHBOR_TO_ROOT":  11,
	"NEIGHBOR_AND_BACK": 12,
	"PARENT_AND_BACK":   22,
}

func (x ForwardingType) String() string {
	return proto.EnumName(ForwardingType_name, int32(x))
}
func (ForwardingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_2fa6fd7701db247e, []int{0}
}

type HeaderType int32

const (
	HeaderType_NO_HEADER              HeaderType = 0
	HeaderType_BASIC                  HeaderType = 1
	HeaderType_DATA_BYTE              HeaderType = 2
	HeaderType_LITTLE_BIG_ENDIAN_SYNC HeaderType = 15
)

var HeaderType_name = map[int32]string{
	0:  "NO_HEADER",
	1:  "BASIC",
	2:  "DATA_BYTE",
	15: "LITTLE_BIG_ENDIAN_SYNC",
}
var HeaderType_value = map[string]int32{
	"NO_HEADER":              0,
	"BASIC":                  1,
	"DATA_BYTE":              2,
	"LITTLE_BIG_ENDIAN_SYNC": 15,
}

func (x HeaderType) String() string {
	return proto.EnumName(HeaderType_name, int32(x))
}
func (HeaderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_2fa6fd7701db247e, []int{1}
}

type ProtobufType int32

const (
	ProtobufType_NO_PROTOBUF            ProtobufType = 0
	ProtobufType_PING                   ProtobufType = 1
	ProtobufType_TIMESYNC               ProtobufType = 2
	ProtobufType_PONG                   ProtobufType = 3
	ProtobufType_MESH_TOPOLOGY          ProtobufType = 4
	ProtobufType_INFO                   ProtobufType = 5
	ProtobufType_LOG                    ProtobufType = 6
	ProtobufType_SYNC_LITTLE_BIG_ENDIAN ProtobufType = 15
)

var ProtobufType_name = map[int32]string{
	0:  "NO_PROTOBUF",
	1:  "PING",
	2:  "TIMESYNC",
	3:  "PONG",
	4:  "MESH_TOPOLOGY",
	5:  "INFO",
	6:  "LOG",
	15: "SYNC_LITTLE_BIG_ENDIAN",
}
var ProtobufType_value = map[string]int32{
	"NO_PROTOBUF":   0,
	"PING":          1,
	"TIMESYNC":      2,
	"PONG":          3,
	"MESH_TOPOLOGY": 4,
	"INFO":          5,
	"LOG":           6,
	"SYNC_LITTLE_BIG_ENDIAN": 15,
}

func (x ProtobufType) String() string {
	return proto.EnumName(ProtobufType_name, int32(x))
}
func (ProtobufType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_2fa6fd7701db247e, []int{2}
}

type LoggingLevel int32

const (
	LoggingLevel_trace LoggingLevel = 0
	LoggingLevel_debug LoggingLevel = 1
	LoggingLevel_info  LoggingLevel = 2
	LoggingLevel_warn  LoggingLevel = 3
	LoggingLevel_error LoggingLevel = 4
	LoggingLevel_fatal LoggingLevel = 5
)

var LoggingLevel_name = map[int32]string{
	0: "trace",
	1: "debug",
	2: "info",
	3: "warn",
	4: "error",
	5: "fatal",
}
var LoggingLevel_value = map[string]int32{
	"trace": 0,
	"debug": 1,
	"info":  2,
	"warn":  3,
	"error": 4,
	"fatal": 5,
}

func (x LoggingLevel) String() string {
	return proto.EnumName(LoggingLevel_name, int32(x))
}
func (LoggingLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_2fa6fd7701db247e, []int{3}
}

type RespirMeshInfo struct {
	TargetId             uint32       `protobuf:"varint,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	SourceId             uint32       `protobuf:"varint,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Type                 ProtobufType `protobuf:"varint,3,opt,name=type,enum=ProtobufType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RespirMeshInfo) Reset()         { *m = RespirMeshInfo{} }
func (m *RespirMeshInfo) String() string { return proto.CompactTextString(m) }
func (*RespirMeshInfo) ProtoMessage()    {}
func (*RespirMeshInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_2fa6fd7701db247e, []int{0}
}
func (m *RespirMeshInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespirMeshInfo.Unmarshal(m, b)
}
func (m *RespirMeshInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespirMeshInfo.Marshal(b, m, deterministic)
}
func (dst *RespirMeshInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespirMeshInfo.Merge(dst, src)
}
func (m *RespirMeshInfo) XXX_Size() int {
	return xxx_messageInfo_RespirMeshInfo.Size(m)
}
func (m *RespirMeshInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RespirMeshInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RespirMeshInfo proto.InternalMessageInfo

func (m *RespirMeshInfo) GetTargetId() uint32 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *RespirMeshInfo) GetSourceId() uint32 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *RespirMeshInfo) GetType() ProtobufType {
	if m != nil {
		return m.Type
	}
	return ProtobufType_NO_PROTOBUF
}

type RespirMeshLog struct {
	SourceTime uint32 `protobuf:"varint,1,opt,name=source_time,json=sourceTime" json:"source_time,omitempty"`
	SourceId   uint32 `protobuf:"varint,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	// ProtobufType type = 3;
	LogLevel             LoggingLevel `protobuf:"varint,4,opt,name=log_level,json=logLevel,enum=LoggingLevel" json:"log_level,omitempty"`
	Tags                 string       `protobuf:"bytes,5,opt,name=tags" json:"tags,omitempty"`
	Message              string       `protobuf:"bytes,6,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RespirMeshLog) Reset()         { *m = RespirMeshLog{} }
func (m *RespirMeshLog) String() string { return proto.CompactTextString(m) }
func (*RespirMeshLog) ProtoMessage()    {}
func (*RespirMeshLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_2fa6fd7701db247e, []int{1}
}
func (m *RespirMeshLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespirMeshLog.Unmarshal(m, b)
}
func (m *RespirMeshLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespirMeshLog.Marshal(b, m, deterministic)
}
func (dst *RespirMeshLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespirMeshLog.Merge(dst, src)
}
func (m *RespirMeshLog) XXX_Size() int {
	return xxx_messageInfo_RespirMeshLog.Size(m)
}
func (m *RespirMeshLog) XXX_DiscardUnknown() {
	xxx_messageInfo_RespirMeshLog.DiscardUnknown(m)
}

var xxx_messageInfo_RespirMeshLog proto.InternalMessageInfo

func (m *RespirMeshLog) GetSourceTime() uint32 {
	if m != nil {
		return m.SourceTime
	}
	return 0
}

func (m *RespirMeshLog) GetSourceId() uint32 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *RespirMeshLog) GetLogLevel() LoggingLevel {
	if m != nil {
		return m.LogLevel
	}
	return LoggingLevel_trace
}

func (m *RespirMeshLog) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *RespirMeshLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RespirMeshTimeSync struct {
	Info                 *RespirMeshInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	RequestSentTime      uint32          `protobuf:"varint,2,opt,name=request_sent_time,json=requestSentTime" json:"request_sent_time,omitempty"`
	ResponseArriveTime   uint32          `protobuf:"varint,3,opt,name=response_arrive_time,json=responseArriveTime" json:"response_arrive_time,omitempty"`
	ResponseSentTime     uint32          `protobuf:"varint,4,opt,name=response_sent_time,json=responseSentTime" json:"response_sent_time,omitempty"`
	RequestArriveTime    uint32          `protobuf:"varint,5,opt,name=request_arrive_time,json=requestArriveTime" json:"request_arrive_time,omitempty"`
	ServerTimestampUnix  uint32          `protobuf:"varint,6,opt,name=server_timestamp_unix,json=serverTimestampUnix" json:"server_timestamp_unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RespirMeshTimeSync) Reset()         { *m = RespirMeshTimeSync{} }
func (m *RespirMeshTimeSync) String() string { return proto.CompactTextString(m) }
func (*RespirMeshTimeSync) ProtoMessage()    {}
func (*RespirMeshTimeSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_2fa6fd7701db247e, []int{2}
}
func (m *RespirMeshTimeSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespirMeshTimeSync.Unmarshal(m, b)
}
func (m *RespirMeshTimeSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespirMeshTimeSync.Marshal(b, m, deterministic)
}
func (dst *RespirMeshTimeSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespirMeshTimeSync.Merge(dst, src)
}
func (m *RespirMeshTimeSync) XXX_Size() int {
	return xxx_messageInfo_RespirMeshTimeSync.Size(m)
}
func (m *RespirMeshTimeSync) XXX_DiscardUnknown() {
	xxx_messageInfo_RespirMeshTimeSync.DiscardUnknown(m)
}

var xxx_messageInfo_RespirMeshTimeSync proto.InternalMessageInfo

func (m *RespirMeshTimeSync) GetInfo() *RespirMeshInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *RespirMeshTimeSync) GetRequestSentTime() uint32 {
	if m != nil {
		return m.RequestSentTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetResponseArriveTime() uint32 {
	if m != nil {
		return m.ResponseArriveTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetResponseSentTime() uint32 {
	if m != nil {
		return m.ResponseSentTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetRequestArriveTime() uint32 {
	if m != nil {
		return m.RequestArriveTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetServerTimestampUnix() uint32 {
	if m != nil {
		return m.ServerTimestampUnix
	}
	return 0
}

func init() {
	proto.RegisterType((*RespirMeshInfo)(nil), "RespirMeshInfo")
	proto.RegisterType((*RespirMeshLog)(nil), "RespirMeshLog")
	proto.RegisterType((*RespirMeshTimeSync)(nil), "RespirMeshTimeSync")
	proto.RegisterEnum("ForwardingType", ForwardingType_name, ForwardingType_value)
	proto.RegisterEnum("HeaderType", HeaderType_name, HeaderType_value)
	proto.RegisterEnum("ProtobufType", ProtobufType_name, ProtobufType_value)
	proto.RegisterEnum("LoggingLevel", LoggingLevel_name, LoggingLevel_value)
}

func init() { proto.RegisterFile("mesh-packet.proto", fileDescriptor_mesh_packet_2fa6fd7701db247e) }

var fileDescriptor_mesh_packet_2fa6fd7701db247e = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xdd, 0x6e, 0xda, 0x48,
	0x14, 0xc7, 0x63, 0x30, 0x5f, 0x87, 0xaf, 0x61, 0xf2, 0x21, 0xb4, 0x7b, 0xb1, 0xd9, 0xec, 0x4d,
	0x84, 0x76, 0xd1, 0x2a, 0x7d, 0x02, 0x03, 0x06, 0xac, 0x3a, 0x1e, 0x62, 0x06, 0x55, 0xe9, 0xcd,
	0xc8, 0x81, 0xc1, 0xb1, 0x0a, 0x36, 0x1d, 0x9b, 0x7c, 0x5c, 0xf7, 0x61, 0xaa, 0x3e, 0x5b, 0x5f,
	0xa2, 0x9a, 0xb1, 0x4d, 0xa8, 0x2a, 0xf5, 0x6e, 0xf8, 0xff, 0xce, 0x9c, 0xff, 0xff, 0x1c, 0x18,
	0xa0, 0xb3, 0xe5, 0xf1, 0xe3, 0x7f, 0x3b, 0x6f, 0xf9, 0x89, 0x27, 0xfd, 0x9d, 0x88, 0x92, 0xe8,
	0x6a, 0x0b, 0x2d, 0x97, 0xc7, 0xbb, 0x40, 0xdc, 0xf2, 0xf8, 0xd1, 0x0a, 0xd7, 0x11, 0xfe, 0x13,
	0x6a, 0x89, 0x27, 0x7c, 0x9e, 0xb0, 0x60, 0xd5, 0xd5, 0x2e, 0xb5, 0xeb, 0xa6, 0x5b, 0x4d, 0x05,
	0x6b, 0x25, 0x61, 0x1c, 0xed, 0xc5, 0x92, 0x4b, 0x58, 0x48, 0x61, 0x2a, 0x58, 0x2b, 0xfc, 0x37,
	0xe8, 0xc9, 0xeb, 0x8e, 0x77, 0x8b, 0x97, 0xda, 0x75, 0xeb, 0xa6, 0xd9, 0x9f, 0x49, 0x87, 0x87,
	0xfd, 0x9a, 0xbe, 0xee, 0xb8, 0xab, 0xd0, 0xd5, 0x57, 0x0d, 0x9a, 0x6f, 0x7e, 0x76, 0xe4, 0xe3,
	0xbf, 0xa0, 0x9e, 0x75, 0x4c, 0x82, 0x2d, 0xcf, 0x0c, 0x21, 0x95, 0x68, 0xb0, 0xe5, 0xbf, 0xb7,
	0xec, 0x41, 0x6d, 0x13, 0xf9, 0x6c, 0xc3, 0x9f, 0xf8, 0xa6, 0xab, 0x67, 0xbe, 0x76, 0xe4, 0xfb,
	0x41, 0xe8, 0xdb, 0x52, 0x74, 0xab, 0x9b, 0x28, 0x3d, 0x61, 0x0c, 0x7a, 0xe2, 0xf9, 0x71, 0xb7,
	0x74, 0xa9, 0x5d, 0xd7, 0x5c, 0x75, 0xc6, 0x5d, 0xa8, 0x6c, 0x79, 0x1c, 0x7b, 0x3e, 0xef, 0x96,
	0x95, 0x9c, 0x7f, 0xbc, 0xfa, 0x56, 0x00, 0xfc, 0x96, 0x54, 0x26, 0x99, 0xbf, 0x86, 0x4b, 0xfc,
	0x0f, 0xe8, 0x41, 0xb8, 0x8e, 0x54, 0xce, 0xfa, 0x4d, 0xbb, 0xff, 0xf3, 0xf2, 0x5c, 0x05, 0x71,
	0x0f, 0x3a, 0x82, 0x7f, 0xde, 0xf3, 0x38, 0x61, 0x31, 0x0f, 0x93, 0x74, 0xb2, 0x34, 0x7a, 0x3b,
	0x03, 0x73, 0x1e, 0x26, 0x6a, 0xbc, 0xff, 0xe1, 0x4c, 0xf0, 0x78, 0x17, 0x85, 0x31, 0x67, 0x9e,
	0x10, 0xc1, 0x53, 0xb6, 0x88, 0xa2, 0x2a, 0xc7, 0x39, 0x33, 0x14, 0x52, 0x37, 0xfe, 0x85, 0x83,
	0x7a, 0xd4, 0x5e, 0x57, 0xf5, 0x28, 0x27, 0x87, 0xfe, 0x7d, 0x38, 0xcd, 0xb3, 0x1c, 0xb7, 0x2f,
	0xa9, 0xf2, 0x3c, 0xe6, 0x51, 0xf7, 0x1b, 0x38, 0x8f, 0xb9, 0x78, 0xe2, 0x42, 0xd5, 0xc5, 0x89,
	0xb7, 0xdd, 0xb1, 0x7d, 0x18, 0xbc, 0xa8, 0xfd, 0x34, 0xdd, 0xd3, 0x14, 0xd2, 0x9c, 0x2d, 0xc2,
	0xe0, 0xa5, 0xf7, 0x5d, 0x83, 0xd6, 0x38, 0x12, 0xcf, 0x9e, 0x58, 0x05, 0xa1, 0x2f, 0xbf, 0x6e,
	0xdc, 0x02, 0x08, 0x23, 0x36, 0x26, 0xee, 0x07, 0xc3, 0x1d, 0xa1, 0x13, 0x5c, 0x87, 0x0a, 0x25,
	0xcc, 0x25, 0x84, 0x22, 0x0d, 0x9f, 0x01, 0x72, 0xa9, 0xc3, 0xa6, 0xa6, 0x31, 0x32, 0x5d, 0x76,
	0xb7, 0x30, 0x17, 0x26, 0x2a, 0xe0, 0x73, 0xe8, 0x50, 0xc2, 0x66, 0x86, 0x6b, 0x3a, 0x94, 0xe5,
	0xc5, 0x45, 0xdc, 0x84, 0xda, 0x41, 0x46, 0x3a, 0x6e, 0x40, 0x95, 0x12, 0x36, 0x9c, 0x5a, 0xf6,
	0x08, 0x95, 0x30, 0x82, 0x06, 0x25, 0xcc, 0x31, 0xad, 0xc9, 0x74, 0x40, 0xdc, 0x39, 0x2a, 0x67,
	0x46, 0x0e, 0x19, 0x99, 0xa8, 0x82, 0x3b, 0xd0, 0xcc, 0x19, 0x9b, 0x53, 0x32, 0x43, 0x20, 0xbd,
	0x0f, 0x52, 0x6e, 0x52, 0x97, 0xde, 0x07, 0xd5, 0x70, 0x46, 0x6c, 0x60, 0x0c, 0xdf, 0xa3, 0x06,
	0x3e, 0x85, 0x76, 0x96, 0xe7, 0x20, 0x5e, 0xf4, 0xee, 0x00, 0xa6, 0xdc, 0x5b, 0x71, 0xa1, 0x06,
	0x6d, 0x42, 0xcd, 0x21, 0xd9, 0x28, 0xe8, 0x04, 0xd7, 0xa0, 0x34, 0x30, 0xe6, 0xd6, 0x10, 0x69,
	0x92, 0x8c, 0x0c, 0x6a, 0xb0, 0xc1, 0x3d, 0x95, 0xe3, 0xfd, 0x01, 0x17, 0xb6, 0x45, 0xa9, 0x6d,
	0xb2, 0x81, 0x35, 0x61, 0xa6, 0x33, 0xb2, 0x0c, 0x87, 0xcd, 0xef, 0x9d, 0x21, 0x6a, 0xf7, 0xbe,
	0x68, 0xd0, 0x38, 0x7e, 0x2d, 0xb8, 0x0d, 0x75, 0x87, 0xb0, 0x99, 0x4b, 0x28, 0x19, 0x2c, 0xc6,
	0xe8, 0x04, 0x57, 0x41, 0x9f, 0x59, 0xce, 0x04, 0x69, 0x6a, 0x01, 0xd6, 0xad, 0xa9, 0x6e, 0x16,
	0x94, 0x4e, 0x9c, 0x09, 0x2a, 0xca, 0x59, 0x6f, 0xcd, 0xf9, 0x94, 0x51, 0x32, 0x23, 0x36, 0x99,
	0xdc, 0x23, 0x5d, 0x42, 0xcb, 0x19, 0x13, 0x54, 0xc2, 0x15, 0x28, 0xda, 0x64, 0x82, 0xca, 0x32,
	0x85, 0xbc, 0xc9, 0x7e, 0x89, 0x82, 0xda, 0x3d, 0x07, 0x1a, 0xc7, 0x4f, 0x47, 0xce, 0x92, 0x08,
	0x6f, 0xc9, 0xd3, 0xb1, 0x56, 0xfc, 0x61, 0xef, 0x23, 0x4d, 0x36, 0x95, 0x3f, 0xf2, 0xd4, 0xfb,
	0xd9, 0x13, 0x21, 0x2a, 0x4a, 0xcc, 0x85, 0x88, 0x04, 0xd2, 0xe5, 0x71, 0xed, 0x25, 0xde, 0x06,
	0x95, 0x06, 0xa5, 0x8f, 0x45, 0xc1, 0xb7, 0x0f, 0x65, 0xf5, 0x4f, 0xf3, 0xee, 0x47, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x4f, 0x78, 0xbf, 0x9e, 0x7e, 0x04, 0x00, 0x00,
}
