// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mesh-packet.proto

package rem

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ForwardingType int32

const (
	ForwardingType_TO_ROOT           ForwardingType = 0
	ForwardingType_RTN_HEADER_QUEUE  ForwardingType = 1
	ForwardingType_PARENT_TO_ROOT    ForwardingType = 3
	ForwardingType_TO_PARENT         ForwardingType = 4
	ForwardingType_TO_CHILD          ForwardingType = 5
	ForwardingType_TO_NEIGHBOR       ForwardingType = 6
	ForwardingType_TO_NODE           ForwardingType = 7
	ForwardingType_NEIGHBOR_STOP     ForwardingType = 10
	ForwardingType_NEIGHBOR_TO_ROOT  ForwardingType = 11
	ForwardingType_NEIGHBOR_AND_BACK ForwardingType = 12
	ForwardingType_PARENT_AND_BACK   ForwardingType = 22
)

var ForwardingType_name = map[int32]string{
	0:  "TO_ROOT",
	1:  "RTN_HEADER_QUEUE",
	3:  "PARENT_TO_ROOT",
	4:  "TO_PARENT",
	5:  "TO_CHILD",
	6:  "TO_NEIGHBOR",
	7:  "TO_NODE",
	10: "NEIGHBOR_STOP",
	11: "NEIGHBOR_TO_ROOT",
	12: "NEIGHBOR_AND_BACK",
	22: "PARENT_AND_BACK",
}
var ForwardingType_value = map[string]int32{
	"TO_ROOT":           0,
	"RTN_HEADER_QUEUE":  1,
	"PARENT_TO_ROOT":    3,
	"TO_PARENT":         4,
	"TO_CHILD":          5,
	"TO_NEIGHBOR":       6,
	"TO_NODE":           7,
	"NEIGHBOR_STOP":     10,
	"NEIGHBOR_TO_ROOT":  11,
	"NEIGHBOR_AND_BACK": 12,
	"PARENT_AND_BACK":   22,
}

func (x ForwardingType) String() string {
	return proto.EnumName(ForwardingType_name, int32(x))
}
func (ForwardingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_b02473e5aea82481, []int{0}
}

type HeaderType int32

const (
	HeaderType_BASIC                  HeaderType = 0
	HeaderType_LITTLE_BIG_ENDIAN_SYNC HeaderType = 15
)

var HeaderType_name = map[int32]string{
	0:  "BASIC",
	15: "LITTLE_BIG_ENDIAN_SYNC",
}
var HeaderType_value = map[string]int32{
	"BASIC":                  0,
	"LITTLE_BIG_ENDIAN_SYNC": 15,
}

func (x HeaderType) String() string {
	return proto.EnumName(HeaderType_name, int32(x))
}
func (HeaderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_b02473e5aea82481, []int{1}
}

type ProtobufType int32

const (
	ProtobufType_NO_PROTOBUF            ProtobufType = 0
	ProtobufType_PING                   ProtobufType = 1
	ProtobufType_TIMESYNC               ProtobufType = 2
	ProtobufType_PONG                   ProtobufType = 3
	ProtobufType_MESH_TOPOLOGY          ProtobufType = 4
	ProtobufType_INFO                   ProtobufType = 5
	ProtobufType_SYNC_LITTLE_BIG_ENDIAN ProtobufType = 15
)

var ProtobufType_name = map[int32]string{
	0:  "NO_PROTOBUF",
	1:  "PING",
	2:  "TIMESYNC",
	3:  "PONG",
	4:  "MESH_TOPOLOGY",
	5:  "INFO",
	15: "SYNC_LITTLE_BIG_ENDIAN",
}
var ProtobufType_value = map[string]int32{
	"NO_PROTOBUF":   0,
	"PING":          1,
	"TIMESYNC":      2,
	"PONG":          3,
	"MESH_TOPOLOGY": 4,
	"INFO":          5,
	"SYNC_LITTLE_BIG_ENDIAN": 15,
}

func (x ProtobufType) String() string {
	return proto.EnumName(ProtobufType_name, int32(x))
}
func (ProtobufType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_b02473e5aea82481, []int{2}
}

type RespirMeshInfo struct {
	TargetId             uint32       `protobuf:"varint,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	SourceId             uint32       `protobuf:"varint,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Type                 ProtobufType `protobuf:"varint,3,opt,name=type,enum=ProtobufType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RespirMeshInfo) Reset()         { *m = RespirMeshInfo{} }
func (m *RespirMeshInfo) String() string { return proto.CompactTextString(m) }
func (*RespirMeshInfo) ProtoMessage()    {}
func (*RespirMeshInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_b02473e5aea82481, []int{0}
}
func (m *RespirMeshInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespirMeshInfo.Unmarshal(m, b)
}
func (m *RespirMeshInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespirMeshInfo.Marshal(b, m, deterministic)
}
func (dst *RespirMeshInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespirMeshInfo.Merge(dst, src)
}
func (m *RespirMeshInfo) XXX_Size() int {
	return xxx_messageInfo_RespirMeshInfo.Size(m)
}
func (m *RespirMeshInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RespirMeshInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RespirMeshInfo proto.InternalMessageInfo

func (m *RespirMeshInfo) GetTargetId() uint32 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *RespirMeshInfo) GetSourceId() uint32 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *RespirMeshInfo) GetType() ProtobufType {
	if m != nil {
		return m.Type
	}
	return ProtobufType_NO_PROTOBUF
}

type RespirMeshTimeSync struct {
	Info                 *RespirMeshInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	RequestSentTime      uint32          `protobuf:"varint,2,opt,name=request_sent_time,json=requestSentTime" json:"request_sent_time,omitempty"`
	ResponseArriveTime   uint32          `protobuf:"varint,3,opt,name=response_arrive_time,json=responseArriveTime" json:"response_arrive_time,omitempty"`
	ResponseSentTime     uint32          `protobuf:"varint,4,opt,name=response_sent_time,json=responseSentTime" json:"response_sent_time,omitempty"`
	RequestArriveTime    uint32          `protobuf:"varint,5,opt,name=request_arrive_time,json=requestArriveTime" json:"request_arrive_time,omitempty"`
	ServerTimestampUnix  uint32          `protobuf:"varint,6,opt,name=server_timestamp_unix,json=serverTimestampUnix" json:"server_timestamp_unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RespirMeshTimeSync) Reset()         { *m = RespirMeshTimeSync{} }
func (m *RespirMeshTimeSync) String() string { return proto.CompactTextString(m) }
func (*RespirMeshTimeSync) ProtoMessage()    {}
func (*RespirMeshTimeSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_b02473e5aea82481, []int{1}
}
func (m *RespirMeshTimeSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespirMeshTimeSync.Unmarshal(m, b)
}
func (m *RespirMeshTimeSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespirMeshTimeSync.Marshal(b, m, deterministic)
}
func (dst *RespirMeshTimeSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespirMeshTimeSync.Merge(dst, src)
}
func (m *RespirMeshTimeSync) XXX_Size() int {
	return xxx_messageInfo_RespirMeshTimeSync.Size(m)
}
func (m *RespirMeshTimeSync) XXX_DiscardUnknown() {
	xxx_messageInfo_RespirMeshTimeSync.DiscardUnknown(m)
}

var xxx_messageInfo_RespirMeshTimeSync proto.InternalMessageInfo

func (m *RespirMeshTimeSync) GetInfo() *RespirMeshInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *RespirMeshTimeSync) GetRequestSentTime() uint32 {
	if m != nil {
		return m.RequestSentTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetResponseArriveTime() uint32 {
	if m != nil {
		return m.ResponseArriveTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetResponseSentTime() uint32 {
	if m != nil {
		return m.ResponseSentTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetRequestArriveTime() uint32 {
	if m != nil {
		return m.RequestArriveTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetServerTimestampUnix() uint32 {
	if m != nil {
		return m.ServerTimestampUnix
	}
	return 0
}

func init() {
	proto.RegisterType((*RespirMeshInfo)(nil), "RespirMeshInfo")
	proto.RegisterType((*RespirMeshTimeSync)(nil), "RespirMeshTimeSync")
	proto.RegisterEnum("ForwardingType", ForwardingType_name, ForwardingType_value)
	proto.RegisterEnum("HeaderType", HeaderType_name, HeaderType_value)
	proto.RegisterEnum("ProtobufType", ProtobufType_name, ProtobufType_value)
}

func init() { proto.RegisterFile("mesh-packet.proto", fileDescriptor_mesh_packet_b02473e5aea82481) }

var fileDescriptor_mesh_packet_b02473e5aea82481 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x93, 0xcd, 0x6e, 0xda, 0x40,
	0x14, 0x85, 0xe3, 0x60, 0xf2, 0x73, 0x09, 0x78, 0x98, 0xfc, 0x28, 0x6a, 0x37, 0x69, 0xba, 0x89,
	0x50, 0x8b, 0xaa, 0xe4, 0x09, 0x6c, 0x70, 0x60, 0x54, 0x98, 0x71, 0xed, 0x61, 0x91, 0x6e, 0x46,
	0x0e, 0x0c, 0x89, 0x55, 0xf9, 0xa7, 0x63, 0x93, 0x86, 0xbe, 0x51, 0x9f, 0xa8, 0xaf, 0x53, 0x79,
	0x8c, 0x29, 0x55, 0xb7, 0xe7, 0x3b, 0xf7, 0x9e, 0x73, 0x2d, 0x0f, 0x74, 0x63, 0x99, 0x3f, 0x7f,
	0xcc, 0xc2, 0xf9, 0x37, 0x59, 0xf4, 0x33, 0x95, 0x16, 0xe9, 0x75, 0x0c, 0x1d, 0x5f, 0xe6, 0x59,
	0xa4, 0xa6, 0x32, 0x7f, 0x26, 0xc9, 0x32, 0xc5, 0x6f, 0xe1, 0xb8, 0x08, 0xd5, 0x93, 0x2c, 0x44,
	0xb4, 0xb8, 0x34, 0xae, 0x8c, 0x9b, 0xb6, 0x7f, 0x54, 0x09, 0x64, 0x51, 0xc2, 0x3c, 0x5d, 0xa9,
	0xb9, 0x2c, 0xe1, 0x7e, 0x05, 0x2b, 0x81, 0x2c, 0xf0, 0x3b, 0x30, 0x8b, 0x75, 0x26, 0x2f, 0x1b,
	0x57, 0xc6, 0x4d, 0xe7, 0xb6, 0xdd, 0xf7, 0xca, 0x84, 0xc7, 0xd5, 0x92, 0xaf, 0x33, 0xe9, 0x6b,
	0x74, 0xfd, 0x6b, 0x1f, 0xf0, 0xdf, 0x3c, 0x1e, 0xc5, 0x32, 0x58, 0x27, 0x73, 0xfc, 0x1e, 0xcc,
	0x28, 0x59, 0xa6, 0x3a, 0xae, 0x75, 0x6b, 0xf5, 0xff, 0xad, 0xe4, 0x6b, 0x88, 0x7b, 0xd0, 0x55,
	0xf2, 0xfb, 0x4a, 0xe6, 0x85, 0xc8, 0x65, 0x52, 0x88, 0x22, 0x8a, 0xe5, 0xa6, 0x83, 0xb5, 0x01,
	0x81, 0x4c, 0x8a, 0x72, 0x29, 0xfe, 0x04, 0x67, 0x4a, 0xe6, 0x59, 0x9a, 0xe4, 0x52, 0x84, 0x4a,
	0x45, 0x2f, 0xb2, 0xb2, 0x37, 0xb4, 0x1d, 0xd7, 0xcc, 0xd6, 0x48, 0x4f, 0x7c, 0x80, 0xad, 0xba,
	0xb3, 0xde, 0xd4, 0x7e, 0x54, 0x93, 0xed, 0xfe, 0x3e, 0x9c, 0xd6, 0x5d, 0x76, 0xd7, 0x37, 0xb5,
	0xbd, 0xae, 0xb9, 0xb3, 0xfd, 0x16, 0xce, 0x73, 0xa9, 0x5e, 0xa4, 0xd2, 0xbe, 0xbc, 0x08, 0xe3,
	0x4c, 0xac, 0x92, 0xe8, 0xf5, 0xf2, 0x40, 0x4f, 0x9c, 0x56, 0x90, 0xd7, 0x6c, 0x96, 0x44, 0xaf,
	0xbd, 0xdf, 0x06, 0x74, 0xee, 0x53, 0xf5, 0x23, 0x54, 0x8b, 0x28, 0x79, 0x2a, 0x3f, 0x22, 0x6e,
	0xc1, 0x21, 0x67, 0xc2, 0x67, 0x8c, 0xa3, 0x3d, 0x7c, 0x06, 0xc8, 0xe7, 0x54, 0x8c, 0x5d, 0x7b,
	0xe8, 0xfa, 0xe2, 0xcb, 0xcc, 0x9d, 0xb9, 0xc8, 0xc0, 0x18, 0x3a, 0x9e, 0xed, 0xbb, 0x94, 0x8b,
	0xda, 0xd9, 0xc0, 0x6d, 0x38, 0xe6, 0x4c, 0x54, 0x32, 0x32, 0xf1, 0x09, 0x1c, 0x71, 0x26, 0x06,
	0x63, 0x32, 0x19, 0xa2, 0x26, 0xb6, 0xa0, 0xc5, 0x99, 0xa0, 0x2e, 0x19, 0x8d, 0x1d, 0xe6, 0xa3,
	0x83, 0x4d, 0x08, 0x65, 0x43, 0x17, 0x1d, 0xe2, 0x2e, 0xb4, 0x6b, 0x24, 0x02, 0xce, 0x3c, 0x04,
	0x65, 0xee, 0x56, 0xaa, 0x33, 0x5a, 0xf8, 0x1c, 0xba, 0x5b, 0xd5, 0xa6, 0x43, 0xe1, 0xd8, 0x83,
	0xcf, 0xe8, 0x04, 0x9f, 0x82, 0xb5, 0xa9, 0xb3, 0x15, 0x2f, 0x7a, 0x77, 0x00, 0x63, 0x19, 0x2e,
	0xa4, 0xd2, 0x47, 0x1d, 0x43, 0xd3, 0xb1, 0x03, 0x32, 0x40, 0x7b, 0xf8, 0x0d, 0x5c, 0x4c, 0x08,
	0xe7, 0x13, 0x57, 0x38, 0x64, 0x24, 0x5c, 0x3a, 0x24, 0x36, 0x15, 0xc1, 0x03, 0x1d, 0x20, 0xab,
	0xf7, 0x13, 0x4e, 0x76, 0x7f, 0xa8, 0xb2, 0x37, 0x65, 0xc2, 0xf3, 0x19, 0x67, 0xce, 0xec, 0x1e,
	0xed, 0xe1, 0x23, 0x30, 0x3d, 0x42, 0x47, 0xc8, 0xd0, 0x07, 0x92, 0xa9, 0xab, 0x07, 0xf7, 0xb5,
	0xce, 0xe8, 0x08, 0x35, 0xca, 0x63, 0xa6, 0x6e, 0x30, 0x16, 0x9c, 0x79, 0x6c, 0xc2, 0x46, 0x0f,
	0xc8, 0x2c, 0x21, 0xa1, 0xf7, 0x0c, 0x35, 0xcb, 0xec, 0x72, 0x40, 0xfc, 0x57, 0x00, 0x59, 0x4e,
	0xf3, 0x6b, 0x43, 0xc9, 0xf8, 0xf1, 0x40, 0xbf, 0x99, 0xbb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x20, 0x97, 0xed, 0xf1, 0x48, 0x03, 0x00, 0x00,
}
