// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mesh-packet.proto

package rem

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ForwardingType int32

const (
	ForwardingType_no_FORWARD        ForwardingType = 0
	ForwardingType_TO_ROOT           ForwardingType = 1
	ForwardingType_RTN_HEADER_QUEUE  ForwardingType = 2
	ForwardingType_TO_PARENT_TO_ROOT ForwardingType = 3
	ForwardingType_TO_PARENT         ForwardingType = 4
	ForwardingType_TO_CHILD          ForwardingType = 5
	ForwardingType_TO_NEIGHBORS      ForwardingType = 6
	ForwardingType_TO_NODE           ForwardingType = 7
	ForwardingType_NEIGHBOR_STOP     ForwardingType = 10
	ForwardingType_NEIGHBOR_TO_ROOT  ForwardingType = 11
	ForwardingType_NEIGHBOR_AND_BACK ForwardingType = 12
	ForwardingType_PARENT_AND_BACK   ForwardingType = 22
)

var ForwardingType_name = map[int32]string{
	0:  "no_FORWARD",
	1:  "TO_ROOT",
	2:  "RTN_HEADER_QUEUE",
	3:  "TO_PARENT_TO_ROOT",
	4:  "TO_PARENT",
	5:  "TO_CHILD",
	6:  "TO_NEIGHBORS",
	7:  "TO_NODE",
	10: "NEIGHBOR_STOP",
	11: "NEIGHBOR_TO_ROOT",
	12: "NEIGHBOR_AND_BACK",
	22: "PARENT_AND_BACK",
}
var ForwardingType_value = map[string]int32{
	"no_FORWARD":        0,
	"TO_ROOT":           1,
	"RTN_HEADER_QUEUE":  2,
	"TO_PARENT_TO_ROOT": 3,
	"TO_PARENT":         4,
	"TO_CHILD":          5,
	"TO_NEIGHBORS":      6,
	"TO_NODE":           7,
	"NEIGHBOR_STOP":     10,
	"NEIGHBOR_TO_ROOT":  11,
	"NEIGHBOR_AND_BACK": 12,
	"PARENT_AND_BACK":   22,
}

func (x ForwardingType) String() string {
	return proto.EnumName(ForwardingType_name, int32(x))
}
func (ForwardingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_c6dab7643c32a278, []int{0}
}

type HeaderType int32

const (
	HeaderType_NO_HEADER              HeaderType = 0
	HeaderType_BASIC                  HeaderType = 1
	HeaderType_DATA_BYTE              HeaderType = 2
	HeaderType_LITTLE_BIG_ENDIAN_SYNC HeaderType = 15
)

var HeaderType_name = map[int32]string{
	0:  "NO_HEADER",
	1:  "BASIC",
	2:  "DATA_BYTE",
	15: "LITTLE_BIG_ENDIAN_SYNC",
}
var HeaderType_value = map[string]int32{
	"NO_HEADER":              0,
	"BASIC":                  1,
	"DATA_BYTE":              2,
	"LITTLE_BIG_ENDIAN_SYNC": 15,
}

func (x HeaderType) String() string {
	return proto.EnumName(HeaderType_name, int32(x))
}
func (HeaderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_c6dab7643c32a278, []int{1}
}

type ProtobufType int32

const (
	ProtobufType_NO_PROTOBUF            ProtobufType = 0
	ProtobufType_PING                   ProtobufType = 1
	ProtobufType_TIMESYNC               ProtobufType = 2
	ProtobufType_PONG                   ProtobufType = 3
	ProtobufType_MESH_TOPOLOGY          ProtobufType = 4
	ProtobufType_INFO                   ProtobufType = 5
	ProtobufType_LOG                    ProtobufType = 6
	ProtobufType_SYNC_LITTLE_BIG_ENDIAN ProtobufType = 15
)

var ProtobufType_name = map[int32]string{
	0:  "NO_PROTOBUF",
	1:  "PING",
	2:  "TIMESYNC",
	3:  "PONG",
	4:  "MESH_TOPOLOGY",
	5:  "INFO",
	6:  "LOG",
	15: "SYNC_LITTLE_BIG_ENDIAN",
}
var ProtobufType_value = map[string]int32{
	"NO_PROTOBUF":   0,
	"PING":          1,
	"TIMESYNC":      2,
	"PONG":          3,
	"MESH_TOPOLOGY": 4,
	"INFO":          5,
	"LOG":           6,
	"SYNC_LITTLE_BIG_ENDIAN": 15,
}

func (x ProtobufType) String() string {
	return proto.EnumName(ProtobufType_name, int32(x))
}
func (ProtobufType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_c6dab7643c32a278, []int{2}
}

// 0       Emergency           emerg
// 1       Alert               alert
// 2       Critical            crit
// 3       Error               err
// 4       Warning             warning
// 5       Notice              notice
// 6       Informational       info
// 7       Debug               debug
type Severity int32

const (
	Severity_emerg   Severity = 0
	Severity_alert   Severity = 1
	Severity_crit    Severity = 2
	Severity_err     Severity = 3
	Severity_warning Severity = 4
	Severity_notice  Severity = 5
	Severity_info    Severity = 6
	Severity_debug   Severity = 7
)

var Severity_name = map[int32]string{
	0: "emerg",
	1: "alert",
	2: "crit",
	3: "err",
	4: "warning",
	5: "notice",
	6: "info",
	7: "debug",
}
var Severity_value = map[string]int32{
	"emerg":   0,
	"alert":   1,
	"crit":    2,
	"err":     3,
	"warning": 4,
	"notice":  5,
	"info":    6,
	"debug":   7,
}

func (x Severity) String() string {
	return proto.EnumName(Severity_name, int32(x))
}
func (Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_c6dab7643c32a278, []int{3}
}

type RespirMeshInfo struct {
	TargetId             uint32       `protobuf:"varint,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	SourceId             uint32       `protobuf:"varint,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Type                 ProtobufType `protobuf:"varint,3,opt,name=type,enum=ProtobufType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RespirMeshInfo) Reset()         { *m = RespirMeshInfo{} }
func (m *RespirMeshInfo) String() string { return proto.CompactTextString(m) }
func (*RespirMeshInfo) ProtoMessage()    {}
func (*RespirMeshInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_c6dab7643c32a278, []int{0}
}
func (m *RespirMeshInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespirMeshInfo.Unmarshal(m, b)
}
func (m *RespirMeshInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespirMeshInfo.Marshal(b, m, deterministic)
}
func (dst *RespirMeshInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespirMeshInfo.Merge(dst, src)
}
func (m *RespirMeshInfo) XXX_Size() int {
	return xxx_messageInfo_RespirMeshInfo.Size(m)
}
func (m *RespirMeshInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RespirMeshInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RespirMeshInfo proto.InternalMessageInfo

func (m *RespirMeshInfo) GetTargetId() uint32 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *RespirMeshInfo) GetSourceId() uint32 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *RespirMeshInfo) GetType() ProtobufType {
	if m != nil {
		return m.Type
	}
	return ProtobufType_NO_PROTOBUF
}

type RespirMeshLog struct {
	SourceTimestamp      uint32   `protobuf:"varint,1,opt,name=source_timestamp,json=sourceTimestamp" json:"source_timestamp,omitempty"`
	SourceId             uint32   `protobuf:"varint,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	Severity             Severity `protobuf:"varint,4,opt,name=severity,enum=Severity" json:"severity,omitempty"`
	Message              string   `protobuf:"bytes,6,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespirMeshLog) Reset()         { *m = RespirMeshLog{} }
func (m *RespirMeshLog) String() string { return proto.CompactTextString(m) }
func (*RespirMeshLog) ProtoMessage()    {}
func (*RespirMeshLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_c6dab7643c32a278, []int{1}
}
func (m *RespirMeshLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespirMeshLog.Unmarshal(m, b)
}
func (m *RespirMeshLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespirMeshLog.Marshal(b, m, deterministic)
}
func (dst *RespirMeshLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespirMeshLog.Merge(dst, src)
}
func (m *RespirMeshLog) XXX_Size() int {
	return xxx_messageInfo_RespirMeshLog.Size(m)
}
func (m *RespirMeshLog) XXX_DiscardUnknown() {
	xxx_messageInfo_RespirMeshLog.DiscardUnknown(m)
}

var xxx_messageInfo_RespirMeshLog proto.InternalMessageInfo

func (m *RespirMeshLog) GetSourceTimestamp() uint32 {
	if m != nil {
		return m.SourceTimestamp
	}
	return 0
}

func (m *RespirMeshLog) GetSourceId() uint32 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *RespirMeshLog) GetSeverity() Severity {
	if m != nil {
		return m.Severity
	}
	return Severity_emerg
}

func (m *RespirMeshLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RespirMeshTimeSync struct {
	Info                 *RespirMeshInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	RequestSentTime      uint32          `protobuf:"varint,2,opt,name=request_sent_time,json=requestSentTime" json:"request_sent_time,omitempty"`
	ResponseArriveTime   uint32          `protobuf:"varint,3,opt,name=response_arrive_time,json=responseArriveTime" json:"response_arrive_time,omitempty"`
	ResponseSentTime     uint32          `protobuf:"varint,4,opt,name=response_sent_time,json=responseSentTime" json:"response_sent_time,omitempty"`
	RequestArriveTime    uint32          `protobuf:"varint,5,opt,name=request_arrive_time,json=requestArriveTime" json:"request_arrive_time,omitempty"`
	ServerTimestampUnix  uint32          `protobuf:"varint,6,opt,name=server_timestamp_unix,json=serverTimestampUnix" json:"server_timestamp_unix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RespirMeshTimeSync) Reset()         { *m = RespirMeshTimeSync{} }
func (m *RespirMeshTimeSync) String() string { return proto.CompactTextString(m) }
func (*RespirMeshTimeSync) ProtoMessage()    {}
func (*RespirMeshTimeSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_mesh_packet_c6dab7643c32a278, []int{2}
}
func (m *RespirMeshTimeSync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespirMeshTimeSync.Unmarshal(m, b)
}
func (m *RespirMeshTimeSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespirMeshTimeSync.Marshal(b, m, deterministic)
}
func (dst *RespirMeshTimeSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespirMeshTimeSync.Merge(dst, src)
}
func (m *RespirMeshTimeSync) XXX_Size() int {
	return xxx_messageInfo_RespirMeshTimeSync.Size(m)
}
func (m *RespirMeshTimeSync) XXX_DiscardUnknown() {
	xxx_messageInfo_RespirMeshTimeSync.DiscardUnknown(m)
}

var xxx_messageInfo_RespirMeshTimeSync proto.InternalMessageInfo

func (m *RespirMeshTimeSync) GetInfo() *RespirMeshInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *RespirMeshTimeSync) GetRequestSentTime() uint32 {
	if m != nil {
		return m.RequestSentTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetResponseArriveTime() uint32 {
	if m != nil {
		return m.ResponseArriveTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetResponseSentTime() uint32 {
	if m != nil {
		return m.ResponseSentTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetRequestArriveTime() uint32 {
	if m != nil {
		return m.RequestArriveTime
	}
	return 0
}

func (m *RespirMeshTimeSync) GetServerTimestampUnix() uint32 {
	if m != nil {
		return m.ServerTimestampUnix
	}
	return 0
}

func init() {
	proto.RegisterType((*RespirMeshInfo)(nil), "RespirMeshInfo")
	proto.RegisterType((*RespirMeshLog)(nil), "RespirMeshLog")
	proto.RegisterType((*RespirMeshTimeSync)(nil), "RespirMeshTimeSync")
	proto.RegisterEnum("ForwardingType", ForwardingType_name, ForwardingType_value)
	proto.RegisterEnum("HeaderType", HeaderType_name, HeaderType_value)
	proto.RegisterEnum("ProtobufType", ProtobufType_name, ProtobufType_value)
	proto.RegisterEnum("Severity", Severity_name, Severity_value)
}

func init() { proto.RegisterFile("mesh-packet.proto", fileDescriptor_mesh_packet_c6dab7643c32a278) }

var fileDescriptor_mesh_packet_c6dab7643c32a278 = []byte{
	// 698 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdd, 0x6e, 0xf2, 0x36,
	0x18, 0x6e, 0x20, 0xfc, 0xbd, 0x10, 0x30, 0xee, 0x8f, 0xd0, 0x76, 0xd2, 0x75, 0x9a, 0xd4, 0xa1,
	0x0d, 0x4d, 0xdd, 0x15, 0x04, 0x08, 0x10, 0x8d, 0xc6, 0xd4, 0x31, 0x9a, 0xba, 0x13, 0x2b, 0x05,
	0x97, 0x46, 0x1b, 0x09, 0x73, 0x42, 0x5b, 0x8e, 0x77, 0x13, 0xbb, 0x85, 0x5d, 0xdb, 0x6e, 0xe2,
	0x93, 0x4d, 0x92, 0xf2, 0xe9, 0x93, 0xbe, 0xc3, 0x3c, 0xcf, 0xeb, 0xe7, 0xe7, 0xb5, 0x1c, 0xe8,
	0x6e, 0x45, 0xf2, 0xf2, 0xf3, 0x2e, 0x58, 0xfd, 0x29, 0xd2, 0xc1, 0x4e, 0xc6, 0x69, 0x7c, 0xb3,
	0x85, 0x36, 0x15, 0xc9, 0x2e, 0x94, 0xf7, 0x22, 0x79, 0x71, 0xa3, 0xe7, 0x18, 0x7f, 0x0b, 0x8d,
	0x34, 0x90, 0x1b, 0x91, 0xf2, 0x70, 0xdd, 0x33, 0xae, 0x8d, 0x5b, 0x8b, 0xd6, 0x8f, 0x80, 0xbb,
	0x56, 0x64, 0x12, 0xef, 0xe5, 0x4a, 0x28, 0xb2, 0x74, 0x24, 0x8f, 0x80, 0xbb, 0xc6, 0xdf, 0x81,
	0x99, 0x1e, 0x76, 0xa2, 0x57, 0xbe, 0x36, 0x6e, 0xdb, 0x77, 0xd6, 0x60, 0xa1, 0x1c, 0x9e, 0xf6,
	0xcf, 0xec, 0xb0, 0x13, 0x54, 0x53, 0x37, 0xff, 0x1a, 0x60, 0x7d, 0xf8, 0xcd, 0xe3, 0x0d, 0xfe,
	0x11, 0x50, 0xa6, 0x98, 0x86, 0x5b, 0x91, 0xa4, 0xc1, 0x76, 0x97, 0xb9, 0x76, 0x8e, 0x38, 0xcb,
	0xe1, 0xaf, 0x9b, 0xff, 0x00, 0xf5, 0x44, 0xbc, 0x0a, 0x19, 0xa6, 0x87, 0x9e, 0xa9, 0x03, 0x34,
	0x06, 0x7e, 0x06, 0xd0, 0x82, 0xc2, 0x3d, 0xa8, 0x6d, 0x45, 0x92, 0x04, 0x1b, 0xd1, 0xab, 0x5e,
	0x1b, 0xb7, 0x0d, 0x9a, 0x7f, 0xde, 0xfc, 0x57, 0x02, 0xfc, 0x11, 0x4d, 0xb9, 0xfa, 0x87, 0x68,
	0x85, 0xbf, 0x07, 0x33, 0x8c, 0x9e, 0x63, 0x9d, 0xa9, 0x79, 0xd7, 0x19, 0x7c, 0xbe, 0x2d, 0xaa,
	0x49, 0xdc, 0x87, 0xae, 0x14, 0x7f, 0xef, 0x45, 0x92, 0xf2, 0x44, 0x44, 0xa9, 0xae, 0x92, 0x25,
	0xec, 0x64, 0x84, 0x2f, 0xa2, 0x54, 0x89, 0xe2, 0x5f, 0xe0, 0x42, 0x8a, 0x64, 0x17, 0x47, 0x89,
	0xe0, 0x81, 0x94, 0xe1, 0xeb, 0xb1, 0xb9, 0xde, 0x9a, 0x45, 0x71, 0xce, 0xd9, 0x9a, 0xd2, 0x27,
	0x7e, 0x82, 0x02, 0x3d, 0x91, 0x37, 0xf5, 0x3c, 0xca, 0x99, 0x42, 0x7f, 0x00, 0xe7, 0x79, 0x96,
	0x53, 0xf9, 0x8a, 0x1e, 0xcf, 0x63, 0x9e, 0xa8, 0xdf, 0xc1, 0x65, 0x22, 0xe4, 0xab, 0x90, 0x1f,
	0x17, 0xc0, 0xf7, 0x51, 0xf8, 0xae, 0xf7, 0x63, 0xd1, 0xf3, 0x23, 0x59, 0xdc, 0xc2, 0x32, 0x0a,
	0xdf, 0xfb, 0xff, 0x1b, 0xd0, 0x9e, 0xc4, 0xf2, 0x2d, 0x90, 0xeb, 0x30, 0xda, 0xa8, 0xfb, 0xc5,
	0x6d, 0x80, 0x28, 0xe6, 0x13, 0x42, 0x7f, 0xb7, 0xe9, 0x18, 0x9d, 0xe1, 0x26, 0xd4, 0x18, 0xe1,
	0x94, 0x10, 0x86, 0x0c, 0x7c, 0x01, 0x88, 0x32, 0x8f, 0xcf, 0x1c, 0x7b, 0xec, 0x50, 0xfe, 0xb0,
	0x74, 0x96, 0x0e, 0x2a, 0xe1, 0x4b, 0xe8, 0x32, 0xc2, 0x17, 0x36, 0x75, 0x3c, 0xc6, 0xf3, 0xe1,
	0x32, 0xb6, 0xa0, 0x51, 0xc0, 0xc8, 0xc4, 0x2d, 0xa8, 0x33, 0xc2, 0x47, 0x33, 0x77, 0x3e, 0x46,
	0x15, 0x8c, 0xa0, 0xc5, 0x08, 0xf7, 0x1c, 0x77, 0x3a, 0x1b, 0x12, 0xea, 0xa3, 0x6a, 0x66, 0xe4,
	0x91, 0xb1, 0x83, 0x6a, 0xb8, 0x0b, 0x56, 0xce, 0x71, 0x9f, 0x91, 0x05, 0x02, 0xe5, 0x5d, 0x40,
	0xb9, 0x49, 0x53, 0x79, 0x17, 0xa8, 0xed, 0x8d, 0xf9, 0xd0, 0x1e, 0xfd, 0x86, 0x5a, 0xf8, 0x1c,
	0x3a, 0x59, 0x9e, 0x02, 0xbc, 0xea, 0x3f, 0x00, 0xcc, 0x44, 0xb0, 0x16, 0x52, 0x17, 0xb5, 0xa0,
	0xe1, 0x91, 0xac, 0x0a, 0x3a, 0xc3, 0x0d, 0xa8, 0x0c, 0x6d, 0xdf, 0x1d, 0x21, 0x43, 0x31, 0x63,
	0x9b, 0xd9, 0x7c, 0xf8, 0xc8, 0x54, 0xbd, 0x6f, 0xe0, 0x6a, 0xee, 0x32, 0x36, 0x77, 0xf8, 0xd0,
	0x9d, 0x72, 0xc7, 0x1b, 0xbb, 0xb6, 0xc7, 0xfd, 0x47, 0x6f, 0x84, 0x3a, 0xfd, 0x7f, 0x0c, 0x68,
	0x9d, 0x3e, 0x0f, 0xdc, 0x81, 0xa6, 0x47, 0xf8, 0x82, 0x12, 0x46, 0x86, 0xcb, 0x09, 0x3a, 0xc3,
	0x75, 0x30, 0x17, 0xae, 0x37, 0x45, 0x86, 0x5e, 0x80, 0x7b, 0xef, 0xe8, 0x93, 0x25, 0x8d, 0x13,
	0x6f, 0x8a, 0xca, 0xaa, 0xeb, 0xbd, 0xe3, 0xcf, 0x38, 0x23, 0x0b, 0x32, 0x27, 0xd3, 0x47, 0x64,
	0x2a, 0xd2, 0xf5, 0x26, 0x04, 0x55, 0x70, 0x0d, 0xca, 0x73, 0x32, 0x45, 0x55, 0x95, 0x42, 0x9d,
	0xe4, 0x5f, 0x44, 0x41, 0x9d, 0x7e, 0x00, 0xf5, 0xfc, 0x89, 0xa8, 0x1e, 0x62, 0x2b, 0xe4, 0xe6,
	0x58, 0x29, 0xf8, 0x4b, 0xc8, 0x14, 0x19, 0x4a, 0x70, 0x25, 0xc3, 0x14, 0x95, 0x94, 0xa0, 0x90,
	0x12, 0x95, 0xd5, 0xbe, 0xdf, 0x02, 0x19, 0x85, 0xd1, 0x06, 0x99, 0x18, 0xa0, 0x1a, 0xc5, 0x69,
	0xb8, 0x12, 0xa8, 0xa2, 0x66, 0xd5, 0x63, 0x40, 0x55, 0x25, 0xb0, 0x16, 0x4f, 0xfb, 0x0d, 0xaa,
	0x0d, 0x2b, 0x7f, 0x94, 0xa5, 0xd8, 0x3e, 0x55, 0xf5, 0xdf, 0xe6, 0xd7, 0x4f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xf7, 0x3f, 0xd9, 0x88, 0x82, 0x04, 0x00, 0x00,
}
